### ISSUE TITLE
Zabbix 1.8.11: cannot import zbx_Template_App_PostgreSQL.xml

### ISSUE THREAD

**Issue by Boran** [k0k/Zabbix#2]
XML file contains errors. Fatal Error 76: Opening and ending tag mismatch: link line 34 and head [ Line: 46 | Column: 10 ]

So I fixed a few closing tags, like on the lines:
<link rel='permalink' href='/k0k/Zabbix/blob/9adfb741978ad97c914efb75c30976976e0f93b1/zbx_Template_App_PostgreSQL.xml' />
 <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

But then:
Fatal Error 41: Specification mandate value for attribute itemscope [ Line: 85 | Column: 32 ]

There seem to be many unclosed divs around that line, and because the indentation is not consistent, its difficult to debug.

Is this version bing used with 1.8.x in production?
Thanks in advance,
Sean

**Comment by k0k** [comment]
Hi Sean,

The XML file were build with Zabbix 1.8.13 and actually work at production on Zabbix 1.8.14 on RHEL6.2, recently to update XML file, please try import again.

**Comment by Boran** [comment]
I upgraded to 1.8.15, then grabbed your file from github again, and the import worked.
Thx.

**Comment by k0k** [comment]
Thank you for using this template,  please feel free to upload any new issue.

**Comment by cal-s** [comment]
1.8.10 here without a problem
